;gen3
PoochyenaFrames:   INCLUDE "gfx/pokemon/poochyena/frames.asm"
MightyenaFrames: INCLUDE "gfx/pokemon/mightyena/frames.asm"
ZigzagoonFrames:   INCLUDE "gfx/pokemon/zigzagoon/frames.asm"
LinooneFrames: INCLUDE "gfx/pokemon/linoone/frames.asm"
WingullFrames:   INCLUDE "gfx/pokemon/wingull/frames.asm"
PelipperFrames: INCLUDE "gfx/pokemon/pelipper/frames.asm"
ShroomishFrames:   INCLUDE "gfx/pokemon/shroomish/frames.asm"
BreloomFrames: INCLUDE "gfx/pokemon/breloom/frames.asm"
SkittyFrames:   INCLUDE "gfx/pokemon/skitty/frames.asm"
DelcattyFrames: INCLUDE "gfx/pokemon/delcatty/frames.asm"
ElectrikeFrames:   INCLUDE "gfx/pokemon/electrike/frames.asm"
ManectricFrames: INCLUDE "gfx/pokemon/manectric/frames.asm"
TorkoalFrames: INCLUDE "gfx/pokemon/torkoal/frames.asm"
TrapinchFrames: INCLUDE "gfx/pokemon/trapinch/frames.asm"
VibravaFrames:   INCLUDE "gfx/pokemon/vibrava/frames.asm"
FlygonFrames: INCLUDE "gfx/pokemon/flygon/frames.asm"
SwabluFrames:   INCLUDE "gfx/pokemon/swablu/frames.asm"
AltariaFrames: INCLUDE "gfx/pokemon/altaria/frames.asm"
FeebasFrames:   INCLUDE "gfx/pokemon/feebas/frames.asm"
MiloticFrames: INCLUDE "gfx/pokemon/milotic/frames.asm"
;gen4
HonchkrowFrames: INCLUDE "gfx/pokemon/honchkrow/frames.asm"
BronzorFrames: INCLUDE "gfx/pokemon/bronzor/frames.asm"
BronzongFrames:  INCLUDE "gfx/pokemon/bronzong/frames.asm"
TogekissFrames: INCLUDE "gfx/pokemon/togekiss/frames.asm"
LeafeonFrames:   INCLUDE "gfx/pokemon/leafeon/frames.asm"
GlaceonFrames: INCLUDE "gfx/pokemon/glaceon/frames.asm"
MamoswineFrames: INCLUDE "gfx/pokemon/mamoswine/frames.asm"
;gen5
JoltikFrames: INCLUDE "gfx/pokemon/joltik/frames.asm"
GalvantulaFrames: INCLUDE "gfx/pokemon/galvantula/frames.asm"
LarvestaFrames: INCLUDE "gfx/pokemon/larvesta/frames.asm"
VolcaronaFrames: INCLUDE "gfx/pokemon/volcarona/frames.asm"
;gen6
InkayFrames:   INCLUDE "gfx/pokemon/inkay/frames.asm"
MalamarFrames: INCLUDE "gfx/pokemon/malamar/frames.asm"
;gen7
PikipekFrames:   INCLUDE "gfx/pokemon/pikipek/frames.asm"
TrumbeakFrames: INCLUDE "gfx/pokemon/trumbeak/frames.asm"
ToucannonFrames: INCLUDE "gfx/pokemon/toucannon/frames.asm"
;gen8
ApplinFrames:   INCLUDE "gfx/pokemon/applin/frames.asm"
AppletunFrames: INCLUDE "gfx/pokemon/appletun/frames.asm"
FlappleFrames: INCLUDE "gfx/pokemon/flapple/frames.asm"
FalinksFrames:  INCLUDE "gfx/pokemon/falinks/frames.asm"
WyrdeerFrames:  INCLUDE "gfx/pokemon/wyrdeer/frames.asm"
UrsalunaFrames:  INCLUDE "gfx/pokemon/ursaluna/frames.asm"
;gen9
MaschiffFrames: INCLUDE "gfx/pokemon/maschiff/frames.asm"
MabosstiffFrames:  INCLUDE "gfx/pokemon/mabosstiff/frames.asm"
FlittleFrames: INCLUDE "gfx/pokemon/flittle/frames.asm"
EspathraFrames:  INCLUDE "gfx/pokemon/espathra/frames.asm"
PwooperFrames: INCLUDE "gfx/pokemon/pwooper/frames.asm"
ClodsireFrames:  INCLUDE "gfx/pokemon/clodsire/frames.asm"
ChiyuFrames:  INCLUDE "gfx/pokemon/chi_yu/frames.asm"
ErsrheadbbyFrames:  INCLUDE "gfx/pokemon/ersrheadbby/frames.asm"
